version: '4.0'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  api:
    build:
      context: ./api
    command: sh -c "uvicorn api.scr.app.main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    # depends_on:
    #   - db
    # environment:
    #   - DATABASE_URL=postgresql://hello_fastapi:hello_fastapi@db/hello_fastapi_dev
  frontend:
    build: ./frontend
    ports:
      - 3000:3000 # Маппинг порта из контейнера на хост
    # volumes:
    #   - ./frontend:/app
    # command: sh -c "npm install && npm start"