version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  web:
    build:
      context: .
    command: sh -c "uvicorn scr.app.main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    # depends_on:
    #   - db
    # environment:
    #   - DATABASE_URL=postgresql://hello_fastapi:hello_fastapi@db/hello_fastapi_dev